version: "3"

services:
  php:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./Controleur:/Controleur
      - ./Model:/Model
      - ./Vue:/Vue
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: theo
      POSTGRES_PASSWORD: theo
      POSTGRES_ROOT_PASSWORD: theo
    volumes:
      - ./Model/BDD/BDDSAE.sql:/docker-entrypoint-initdb.d/BDDSAE.sql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - "82:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 5432
      PMA_ARBITRARY: 1

networks:
  app-network:
    driver: bridge
